FROM golang:1.23-alpine AS builder

RUN mkdir /app

COPY . /app

WORKDIR /app

RUN CGO_ENABLED=0 go build -o helpmatch-app ./cmd/api/main.go

FROM alpine:latest

RUN mkdir /app

COPY --from=builder /app/helpmatch-app /app

CMD [ "/app/helpmatch-app" ]