name: help_match
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  web_socket_channel: ^3.0.1
  lottie: ^3.1.3
  font_awesome_flutter: ^10.7.0
  path_provider: ^2.1.5
  smooth_page_indicator: ^1.2.0+3
  fpdart: ^1.1.1
  google_fonts: ^6.2.1
  dio: ^5.7.0
  google_sign_in: ^6.2.2
  flutter_secure_storage: ^9.2.2
  flutter_map: ^7.0.2
  location: ^7.0.1
  latlong2: ^0.9.1
  hive_ce: ^2.9.0
  hive_ce_flutter: ^2.1.0
  shared_preferences: ^2.5.1
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  hive_ce_generator: ^1.8.1

# For information on the generic Dart part of this file, see the
following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/animations/
    - assets/images/
    # - assets/fonts/

  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
