// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:help_match/core/current_user/model/user_cache_model.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(LocationAdapter());
    registerAdapter(OrgInfoAdapter());
    registerAdapter(UserAdapter());
  }
}
